### PR TITLE
fix so readlink will work on platforms that don't have "readlink -f" …

### PR DESCRIPTION
**Pull request by ispringer**
…(e.g. OS X)

### CODE REVIEW

**Comment by patric-r** [comment]
Thanks for the patch, however it does not work on my machine (Linux):
```
./jvmtop.sh
./jvmtop.sh: line 8: cd: ./jvmtop.sh: line 7: greadlink: command not found
```

**Comment by patric-r** [comment]
Thanks, however I am not fully convinced about this solution - sorry about that.

The first thing is that after applying your patch, jvmtop.sh would typically (linux environment) invoke 3 child processes of readlink before it actually suceeds determining its own directory.

Instead, can you try if the following approach would work for you / under OS X:
https://github.com/patric-r/jvmtop/commit/820768503ba3ffc8fa6c9090496c8230c5d1bb4a

**Comment by ispringer** [comment]
No prob. Yeah, that works for me on OS X Yosemite.

**Comment by patric-r** [comment]
Thanks for testing this so quickly. I merged the change into the master branch, and it will be part of the next official jvmtop release. Thank you once again!

**Pull request closed without merging**
